services:
  - type: web
    name: task-master
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: taskmasterdb
          property: connectionString

databases:
  - name: taskmasterdb
    databaseName: taskmaster
    user: taskmaster_user
    plan: free
